RCJ/funcionarios/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from RCJ.funcionarios import views as funcionarios_views

app_name = 'funcionarios'
urlpatterns = [
    
    path('lista_funcionarios/', funcionarios_views.list_funcionarios, name = 'lista_funcionario'),
    path('cadastrar_funcionario/', funcionarios_views.create_funcionario, name = 'cadastro_funcionario'),
    path('editar_funcionario/<slug:slug>-<int:pk>', funcionarios_views.edit_funcionario, name = 'editar_funcionario'),
    path('deletar_funcionario/<slug:slug>-<int:pk>', funcionarios_views.delete_funcionario, name = 'deletar_funcionario'),

]

RCJ/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path


urlpatterns = [
    
    #path('usuarios/', include('RCJ.accounts.urls', namespace = 'accounts')),
    path('', include('RCJ.core.urls', namespace = 'core')),
    path('usuarios/', include('RCJ.accounts.urls', namespace = 'accounts')),
    path('funcionarios/', include('RCJ.funcionarios.urls', namespace = 'funcionarios')),
    path('admin/', admin.site.urls),
]

RCJ/funcionarios/models.py
#from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.db.models import signals
from django.utils.text import slugify
import re
from django.urls import reverse
from django.db import models


class Gestor(models.Model):
    
    nome = models.CharField('Nome', max_length=50)
    
    def __str__(self):
        return self.nome

class Funcionario(models.Model):
    
    CARGO_CHOICES = (
        ('TI', 'TI'),
        ('DIRETORIA', 'DIRETORIA'),
        ('RECURSOS HUMANOS', 'RECURSOS HUMANOS'),
        ('BACKOFFICE', 'BACKOFFICE'),
        ('SUPERVISOR', 'SUPERVISOR'),
        ('OPERADOR', 'OPERADOR')
    )
    
    SEX_CHOICES = (
        ('M', 'MASCULINO'),
        ('F', 'FEMININO')
    )
    ESTADO_CIVIL_CHOICES = (
        ('SOLTEIRO', 'SOLTEIRO'),
        ('CASADO', 'CASADO'),
        ('DIVORCIDADO', 'DIVORCIADO')
    )
    CHILDREN_CHOICES = (
        ('SIM','SIM'),
        ('NAO','NÃO')
    )
    AMOUNT_OF_CHILDREN_CHOICES = (
        (0,'0'),
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
        (6,'6'),
        (7,'7'),
        (8,'8'),
        (9,'9'),
        (10,'10'),   
    )
    DEGREE_OF_INSTITUTION_CHOICES = (
        ('ENSINO FUNDAMENTAL COMPLETO','ENSINO FUNDAMENTAL COMPLETO'),
        ('ENSINO FUNDAMENTAL INCOMPLETO','ENSINO FUNDAMENTAL INCOMPLETO'),
        ('ENSINO MEDIO COMPLETO','ENSINO MÉDIO COMPLETO'),
        ('ENSINO MEDIO COMPLETO','ENSINO MÉDIO INCOMPLETO'),
        ('ENSINO SUPERIOR COMPLETO','ENSINO SUPERIOR COMPLETO'),
        ('ENSINO SUPERIOR INCOMPLETO','ENSINO SUPERIOR INCOMPLETO')
    )
    name = models.CharField('Nome', max_length = 50, null = False, blank = False)
    slug = models.SlugField('Atalho',unique = True)
    date_of_birth = models.DateField('Data de nascimento')
    sex = models.CharField('Sexo', max_length = 1, choices = SEX_CHOICES, null = False, blank = False)
    children = models.CharField('Filhos', max_length = 3, choices = CHILDREN_CHOICES, null = False, blank = False)
    amount_of_children = models.IntegerField('Quantidade de filhos', choices = AMOUNT_OF_CHILDREN_CHOICES, null = False, blank = False, default = 0)
    fathers_name = models.CharField('Nome do pai', max_length = 50, null = False, blank = False)
    mothers_name = models.CharField('Nome da mãe', max_length = 50, null = False, blank = False)
    degree_of_institution = models.CharField('Grau de instituição', max_length = 31, null = False, blank = False)
    cargo = models.CharField('Cargo', max_length = 17, choices = CARGO_CHOICES, null = False, blank = False)
    adress = models.OneToOneField('Endereco', verbose_name=('Endereço'), on_delete=models.CASCADE)
    rg = models.OneToOneField('Rg', verbose_name=('RG'), on_delete = models.CASCADE)
    cpf = models.OneToOneField('Cpf', verbose_name=('CPF'), on_delete = models.CASCADE)
    voter_title = models.OneToOneField('TituloDeEleitor', verbose_name=('Titulo de eleitor'), on_delete = models.CASCADE)
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('funcionario_detail', kwargs={'slug': self.slug})

def funcionario_pre_save_receiver(sender, instance, *args, **kwargs):
    teste = slugify(instance.name) + '-%s'  % instance.cpf.cpf 
    instance.slug = teste
    
pre_save.connect(funcionario_pre_save_receiver, sender = Funcionario)  
     
    
class Endereco(models.Model):
    
    street = models.CharField('Rua', max_length = 50, null = False, blank = False)
    number = models.IntegerField('Numero', null = False, blank = False)
    complement = models.CharField('Complemento', max_length = 50, null = False, blank = False)
    neighborhood = models.CharField('Bairro', max_length = 50, null = False, blank = False)
    city = models.CharField('Cidade', max_length = 50, null = False, blank = False)
    state = models.CharField('Estado', max_length = 50, null = False, blank = False)
    
    def __str__(self):
        return self.street
 
class Rg(models.Model):
    
    rg = models.CharField('RG', max_length = 11, null = False, blank = False, unique = True)
    shipping_date = models.DateField('Data de expedição')
    dispatching_agency = models.CharField('Órgão expeditor', max_length = 10, null = False, blank = False)
    
    def __str__(self):
        return self.rg
    
class Cpf(models.Model):
    
    cpf = models.CharField('CPF', max_length = 11, null = False, blank = False, unique = True)
    
    def __str__(self):
        return self.cpf
    
class TituloDeEleitor(models.Model):

    titulo_de_eleitor = models.CharField('Titulo de eleitor', max_length = 12, null = False, blank = True , unique = True)
    zone = models.CharField('Zona eleitoral', max_length = 12, null = False, blank = True)
    

    

        
    

RCJ/funcionarios/forms.py
from RCJ.funcionarios.models import Funcionario, Endereco, Rg, Cpf, TituloDeEleitor
from django import forms
from django.utils.text import slugify
from django.shortcuts import get_object_or_404


class FuncionarioForm(forms.ModelForm):
    
    class Meta:
        
        model = Funcionario
        exclude = ('rg','cpf','voter_title','adress','slug')

class EnderecoForm(forms.ModelForm):
    
    class Meta:
        
        model = Endereco
        fields = '__all__'
        
        
class RgForm(forms.ModelForm):
        
    class Meta:
        
        model = Rg
        fields = '__all__'
        error_messages = {
            'rg' : {
                'unique' : ("Rg já cadastrado no sistema")
            }
        }
                
class CpfForm(forms.ModelForm):
    
    class Meta:
        
        model = Cpf
        fields = '__all__'
        error_messages = {
            'cpf' : {
                'unique' : ("CPF já cadastrado no sistema")
            }
        }
        
class TituloDeEleitorForm(forms.ModelForm):
    
    class Meta:
        
        model = TituloDeEleitor
        fields = '__all__'
        error_messages = {
            'titulo_de_eleitor' : {
                'unique' : ("Titulo de eleitor já cadastrado no sistema")
            }
        }        

RCJ/funcionarios/views.py
from django.shortcuts import render, redirect, get_object_or_404,reverse
from RCJ.funcionarios.forms import FuncionarioForm, EnderecoForm, RgForm, CpfForm, TituloDeEleitorForm  #FuncionarioTestForm
from RCJ.funcionarios.models import Funcionario, Rg, Cpf, TituloDeEleitor, Endereco, Gestor
from .utils import salva_gestor
    
def create_funcionario(request):
    template_name = 'funcionarios/register_funcionario.html'
    
    if request.method == 'POST':
        form_funcionario = FuncionarioForm(request.POST)
        form_endereco = EnderecoForm(request.POST)
        form_rg = RgForm(request.POST)
        form_cpf = CpfForm(request.POST)
        form_titulo = TituloDeEleitorForm(request.POST)
        nome = request.POST.get('name')
        cargo = request.POST.get('cargo')
        if form_funcionario.is_valid() and form_endereco.is_valid() and form_rg.is_valid() and form_cpf.is_valid() and form_titulo.is_valid():
            print('todos validos')
            funcionario = form_funcionario.save(commit = False)
            endereco = form_endereco.save()
            rg = form_rg.save()
            cpf = form_cpf.save()
            titulo = form_titulo.save()
            funcionario.adress = endereco
            funcionario.rg = rg
            funcionario.cpf = cpf
            funcionario.voter_title = titulo
            funcionario.save()
            salva_gestor(nome,cargo)
            return redirect('funcionarios:lista_funcionario')
    else:
        form_funcionario = FuncionarioForm()
        form_endereco = EnderecoForm()
        form_rg = RgForm()
        form_cpf = CpfForm()
        form_titulo = TituloDeEleitorForm()
    context = {
        'form1': form_funcionario,
        'form2': form_endereco,
        'form3': form_rg,
        'form4': form_cpf,
        'form5': form_titulo,  
    }
    return render(request, template_name, context)
    
def delete_funcionario(request, slug, pk):
    template_name = 'funcionarios/delete_funcionario.html'
    funcionario = get_object_or_404(Funcionario, pk = pk)
    endereco = get_object_or_404(Endereco, pk = pk)
    rg = get_object_or_404(Rg, pk = pk)
    cpf = get_object_or_404(Cpf, pk = pk)
    titulo = get_object_or_404(TituloDeEleitor, pk = pk)
    funcionario.delete()
    endereco.delete()
    rg.delete()
    cpf.delete()
    titulo.delete()
    return redirect('funcionarios:lista_funcionario')
    context = {
        'funcionario': funcionario
    }
    return render(request, template_name, context)

def edit_funcionario(request, slug, pk):
    template_name = 'funcionarios/edit_funcionario.html'
    funcionario = get_object_or_404(Funcionario, pk = pk)
    endereco = get_object_or_404(Endereco, pk = pk)
    rg = get_object_or_404(Rg, pk = pk)
    cpf = get_object_or_404(Cpf, pk = pk)
    titulo = get_object_or_404(TituloDeEleitor, pk = pk)
    if request.method == 'POST':
        form1 = FuncionarioForm(request.POST, instance = funcionario)
        form2 = EnderecoForm(request.POST, instance = endereco)
        form3 = RgForm(request.POST, instance = rg)
        form4 = CpfForm(request.POST, instance = cpf)
        form5 = TituloDeEleitorForm(request.POST, instance = titulo)
        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid() and form5.is_valid():
            funcionario = form1.save(commit = False)
            endereco = form2.save()
            rg = form3.save()
            cpf = form4.save()
            titulo = form5.save()
            funcionario.adress = endereco
            funcionario.rg = rg
            funcionario.cpf = cpf
            funcionario.voter_title = titulo
            funcionario.save()
            
            return redirect('funcionarios:lista_funcionario')
    else:
        form1 = FuncionarioForm(instance = funcionario)
        form2 = EnderecoForm(instance = endereco)
        form3 = RgForm(instance = rg)
        form4 = CpfForm(instance = cpf)
        form5 = TituloDeEleitorForm(instance = titulo)
    context = {
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'form5': form5,
    }
    return render(request, template_name, context)
            

def list_funcionarios(request):
    template_name = 'funcionarios/list_funcionario.html'
    funcionarios = Funcionario.objects.all()
    context = {
        'funcionario_list': funcionarios
    }
    return render(request, template_name, context)    

RCJ/funcionarios/templates/funcionarios/delete_funcionario.html
{% block content %}
<form class="" method="post">
  {% csrf_token %}
  Are you sure want to delete it?
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

RCJ/funcionarios/templates/funcionarios/edit_funcionario.html
{% extends 'accounts/base.html'%}
{% load static%}
{% load widget_tweaks%}
<!-- <link rel="stylesheet" href="estilo/estilo.css"> -->
{% block styles%}
<link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css'%}">
{% endblock %}
{% block title %}Cadastrar Funcionarios{% endblock %}
{% block conteudo %}
<div class="container">
    <div class="panel">
        <div>
            <div class="cadastro_title">
                <p>Cadastro de Funcionarios</p>
            </div>
            <br>
        </div>
        <div class="form">
            <form method="POST" id="form-funcionario">
                {% csrf_token %}
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados do pessoais</p>
                            <br>
                        </div>
                        <br>
                    </div>

                    <div class="form-row">
                        <div class="col">
                            <label>Nome:</label>
                            {% render_field form1.name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Data de nascimento:</label>
                            {% render_field form1.date_of_birth class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Sexo:</label>
                            {% render_field form1.sex class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Filhos:</label>
                            {% render_field form1.children class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Quantidade de filhos:</label>
                            {% render_field form1.amount_of_children class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Nome do pai:</label>
                            {% render_field form1.fathers_name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Escolaridade</label>
                            {% render_field form1.degree_of_institution class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Nome da mãe:</label>
                            {% render_field form1.mothers_name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Cargo</label>
                            {% render_field form1.cargo class+="form-control"%}
                        </div>
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados de endereco</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label>Rua:</label>
                        {% render_field form2.street class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Numero:</label>
                        {% render_field form2.number class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Complemento:</label>
                        {% render_field form2.complement class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Bairro:</label>
                        {% render_field form2.neighborhood class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Cidade:</label>
                        {% render_field form2.city class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Estado:</label>
                        {% render_field form2.state class+="form-control"%}
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Documentação</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Rg:</label>
                        {% render_field form3.rg class+="form-control"%}
                        {% render_field form3.rg.errors %}
                    </div>
                    <div class="col">
                        <label>Data de expedição:</label>
                        {% render_field form3.shipping_date class+="form-control"%}
                        {% render_field form3.shipping_date.errors %}
                    </div>
                    <div class="col">
                        <label>Orgão expeditor:</label>
                        {% render_field form3.dispatching_agency class+="form-control"%}
                        {% render_field form3.dispatching_agency.errors %}
                        
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label>Cpf:</label>
                        {% render_field form4.cpf class+="form-control"%}
                        {% render_field form4.cpf.errors %}
                    </div>
                    <div class="col">
                        <label>Titulo de eleitor:</label>
                        {% render_field form5.titulo_de_eleitor class+="form-control"%}
                        {% render_field form5.titulo_de_eleitor.errors %}
                    </div>
                    <div class="col">
                        <label>Zona:</label>
                        {% render_field form5.zone class+="form-control"%}
                        {% render_field form5.zone.errors %}
                    </div>
                </div>
        </div>
        <br>
        <br>
        <div class="row justify-content-md-center">
            <div class="col col-lg-2"></div>
            <div class="col-md-auto">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
            <div class="col col-lg-2"></div>
        </div>
        <br>
        </form>
    </div>
</div>
</div>
</div>

{% endblock conteudo %}

RCJ/funcionarios/templates/funcionarios/list_funcionario.html
{% extends 'accounts/base.html'%}
{% load static %}
{% load widget_tweaks %}
{% block styles%}
    <link rel="stylesheet" href="{% static 'css/list_user.css' %}">
    <link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css' %}"> 
{% endblock %}
{% block title %}Listagem de usuarios{% endblock %}
{% block conteudo %}
<div class="container">
  <div class="cadastro_title">
    Usuario cadastrado no Sistema
  </div>
  <br>
  <div class="panel">
      <table class="table table-bordered">
        <thead class="thead-light"> 
          <tr>
            <th>Funcionario</th> 
            <th>Usuario</th> 
            <th>Cargo</th>
            <th>Ações</th>
          </tr> 
    </thead>
    <tbody>
      {% for info in funcionario_list %}
      <tr>
        <td>
          {{info.name}}
        </td>
        <td>
          {{info.}}
        </td> 
        <td>
          {{info.cargo}}
        </td> 
        <td>
          <a class="btn-opc" href="{% url 'funcionarios:editar_funcionario' info.slug info.id %}">Editar</a>
          <a class="btn-opc" href="{% url 'funcionarios:deletar_funcionario' info.slug info.id %}">Apagar</a>
        </td>
      </tr>
        {%endfor%} 
    </tbody>
      </table>
</div>
</div>

{% endblock %}

RCJ/funcionarios/templates/funcionarios/register_funcionario.html
{% extends 'accounts/base.html'%}
{% load static%}
{% load widget_tweaks%}
<!-- <link rel="stylesheet" href="estilo/estilo.css"> -->
{% block styles%}
<link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css'%}">
{% endblock %}
{% block title %}Cadastrar Funcionarios{% endblock %}
{% block conteudo %}
<div class="container">
    <div class="panel">
        <div>
            <div class="cadastro_title">
                <p>Cadastro de Funcionarios</p>
            </div>
            <br>
        </div>
        <div class="form">
            <form method="POST" id="form-funcionario">
                {% csrf_token %}
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados do pessoais</p>
                            <br>
                        </div>
                        <br>
                    </div>

                    <div class="form-row">
                        <div class="col">
                            <label>Nome:</label>
                            {% render_field form1.name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Data de nascimento:</label>
                            {% render_field form1.date_of_birth class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Sexo:</label>
                            {% render_field form1.sex class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Filhos:</label>
                            {% render_field form1.children class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Quantidade de filhos:</label>
                            {% render_field form1.amount_of_children class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Nome do pai:</label>
                            {% render_field form1.fathers_name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Escolaridade</label>
                            {% render_field form1.degree_of_institution class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Nome da mãe:</label>
                            {% render_field form1.mothers_name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Cargo</label>
                            {% render_field form1.cargo class+="form-control"%}
                        </div>
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados de endereco</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label>Rua:</label>
                        {% render_field form2.street class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Numero:</label>
                        {% render_field form2.number class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Complemento:</label>
                        {% render_field form2.complement class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Bairro:</label>
                        {% render_field form2.neighborhood class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Cidade:</label>
                        {% render_field form2.city class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Estado:</label>
                        {% render_field form2.state class+="form-control"%}
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Documentação</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Rg:</label>
                        {% render_field form3.rg class+="form-control"%}
                        {% render_field form3.rg.errors %}
                    </div>
                    <div class="col">
                        <label>Data de expedição:</label>
                        {% render_field form3.shipping_date class+="form-control"%}
                        {% render_field form3.shipping_date.errors %}
                    </div>
                    <div class="col">
                        <label>Orgão expeditor:</label>
                        {% render_field form3.dispatching_agency class+="form-control"%}
                        {% render_field form3.dispatching_agency.errors %}
                        
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label>Cpf:</label>
                        {% render_field form4.cpf class+="form-control"%}
                        {% render_field form4.cpf.errors %}
                    </div>
                    <div class="col">
                        <label>Titulo de eleitor:</label>
                        {% render_field form5.titulo_de_eleitor class+="form-control"%}
                        {% render_field form5.titulo_de_eleitor.errors %}
                    </div>
                    <div class="col">
                        <label>Zona:</label>
                        {% render_field form5.zone class+="form-control"%}
                        {% render_field form5.zone.errors %}
                    </div>
                </div>
        </div>
        <br>
        <br>
        <div class="row justify-content-md-center">
            <div class="col col-lg-2"></div>
            <div class="col-md-auto">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
            <div class="col col-lg-2"></div>
        </div>
        <br>
        </form>
    </div>
</div>
</div>
</div>

{% endblock conteudo %}