RCJ/accounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from RCJ.accounts import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    #path('login/', LoginView.as_view(template_name='accounts/login.html'), name = 'login'),
    path('login/', accounts_views.user_login, name='login'),
    path('logout/', accounts_views.user_logout, name = 'logout'),
    path('usuarios-cadastrados/', accounts_views.list_user, name = 'usuarios-cadastrados'),
    path('cadastrar-usuario/', accounts_views.register_user, name = 'cadastro-usuario'),
    path('editar-usuario/<slug:slug>', accounts_views.edit_user, name = 'editar-usuario'),
    path('deletar-usuario/<slug:slug>', accounts_views.delete_user, name = 'deletar-usuario'),
    #path('admin/', admin.site.urls),
]

RCJ/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from RCJ.core import views as core_views

app_name = 'core'
urlpatterns = [
    
    #path('lista_funcionarios/', funcionarios_views.list_funcionarios, name = 'lista_funcionario'),
    path('implantar_ficha/', core_views.implanta_ficha_cliente, name = 'implantar_ficha'),
    path('cadastrar_produto/', core_views.create_produto, name = 'cadastrar_produto'),
    path('fila_clientes/', core_views.fila_clientes, name = 'fila_clientes'),
    path('tratar_cliente/<slug:slug>-<int:pk>', core_views.tratar_clientes, name = 'tratar_cliente'),
    #path('deletar_funcionario/<int:pk>-<slug:slug>', funcionarios_views.delete_funcionario, name = 'deletar_funcionario'),

]

RCJ/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path


urlpatterns = [
    
    #path('usuarios/', include('RCJ.accounts.urls', namespace = 'accounts')),
    path('', include('RCJ.core.urls', namespace = 'core')),
    path('usuarios/', include('RCJ.accounts.urls', namespace = 'accounts')),
    path('funcionarios/', include('RCJ.funcionarios.urls', namespace = 'funcionarios')),
    path('admin/', admin.site.urls),
]

RCJ/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
from django.db import models
from django.urls import reverse
import re
from .utils import unique_slug_generator
from django.db.models import signals
from django.utils.text import slugify
from django.db.models.signals import pre_save

from RCJ.funcionarios.models import Funcionario, Gestor

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    
    NIVEL_CHOICES = (
        (5, 'OPERADOR'),
        (4, 'SUPERVISOR'),
        (3, 'BACKOFFICE'),
        (2, 'RECURSOS HUMANOS'),
        (1, 'DIRETORIA'),
        (0, 'TI')        
    )
    
    username = models.CharField(
        'Usuario', max_length = 30, unique = True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),'O nome de usuario só pode conter letras, digitos ou os '
        'seguintes caracteres: @/./+/-/_', 'invalid')])
    slug = models.SlugField('atalho', max_length = 40, unique = True, null = False, blank = True)
    nivel = models.IntegerField(choices = NIVEL_CHOICES, null = False, blank = False)
    email = models.EmailField('E-mail', unique = True)
    funcionario = models.ForeignKey(Funcionario, verbose_name=('Funcionario'), on_delete=models.CASCADE)
    gestor = models.ForeignKey(Gestor, verbose_name=('Gestor'), on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length = 50, blank = True)
    is_active = models.BooleanField('Esta Ativo?', default = True)
    is_staff = models.BooleanField('É da Equipe?', default = False)
    is_admin = models.BooleanField('É administrador do sistema?', default = False)
    date_joined = models.DateField('Data de Cadastro', auto_now_add = True)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']    
        
    def __str__(self):
        return self.funcionario.name
    
    def get_short_name(self):
        return self.username
    
    def get_full_name(self):
        return str(self)
    
    def get_absolute_url(self):
        return reverse('user_detail', kwargs={'slug': self.slug})
    
    def get_nivel(self):
        return self.nivel
    
    class Meta:
        verbose_name= 'Usuário'
        verbose_name_plural = 'Usuários' 


def usuario_pre_save_receiver(sender, instance, *args, **kwargs):
    #teste = slugify(instance.name) + '-%s'  % instance.cpf.cpf 
    instance.slug = slugify(instance.username)
    
pre_save.connect(usuario_pre_save_receiver, sender = User)  

"""
def user_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
pre_save.connect(user_pre_save_receiver, sender = User)
"""   

RCJ/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from RCJ.accounts.models import User
from django import forms
from django.contrib import messages

class RegisterForm(forms.ModelForm):
    
    password1 = forms.CharField(label = 'Senha', widget = forms.PasswordInput) 
    password2 = forms.CharField(label = 'Confirmação de Senha', widget = forms.PasswordInput)
    
    def clean_user(self):
        
        user = self.cleaned_data['user']
        if User.objects.filter(user = user).exists():
            raise forms.ValidationError('Usuario já existe')
        return user
    
    def clean_password2(self):
        
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação de senha esta incorreta') 
        return password2
    
    def save(self, commit = True):
        
        user = super(RegisterForm, self).save(commit = False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    
    class Meta:
        model = User
        fields = ['username','email', 'nivel', 'funcionario','gestor']
        
class EditAccountForm(forms.ModelForm):
    
    def clean_user(self):
            
        user = self.cleaned_data['user']
        queryset = User.objects.filter(user = user).exclude(pk = self.instance.pk) 
        if queryset.exists():
            raise forms.ValidationError('Usuario já existe')
        return user
    
    class Meta:
        model = User
        fields = ['username','email', 'nivel', 'funcionario','gestor']
        
class SetPasswordCustomForm(SetPasswordForm):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch':("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(label="New password",
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="New password confirmation",
                                    widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                print('oi')
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user
        

RCJ/accounts/views.py
from RCJ.accounts.forms import RegisterForm, EditAccountForm, SetPasswordCustomForm
from RCJ.accounts.models import User
from RCJ.funcionarios.models import Funcionario, Gestor
from RCJ.accounts.decorators import user_perm_ti, user_perm_gestores
from django.shortcuts import render, redirect, get_object_or_404,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse




################################### CRUD USER ################################### 

def register_user(request):
    template_name = 'accounts/register_user.html'
    funcionario = Funcionario.objects.all()
    gestor = Gestor.objects.all()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        print(form.errors)
        if form.is_valid():
            print('formulario valido')
            form.save()
            return redirect('accounts:usuarios-cadastrados')
    else:
        form = RegisterForm()
    context = {
        'form': form,
        'funcionario': funcionario,
        'gestor': gestor
    }
    return render(request, template_name, context)

def edit_user(request, slug):
    template_name = 'accounts/edit_user.html'
    user = get_object_or_404(User, slug = slug)
    if request.method == 'POST':
        form1 = EditAccountForm(request.POST, instance = user)
        form2 = SetPasswordCustomForm(data=request.POST, user = user)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            return redirect('accounts:usuarios-cadastrados')
    else:
        form1 = EditAccountForm(instance = user)
        form2 = SetPasswordCustomForm(user=user)
    context = {
        'form1': form1,
        'form2': form2
        
    }
    return render(request, template_name, context)

#@login_required(login_url='accounts:login') # primeiro verificar se o usuario esta logado
#@user_perm_gestores # segundo verificar se o usuario tem acesso a view

def list_user(request):
    template_name = 'accounts/list_user.html'
    user = User.objects.all()
    context = {
        'user_list': user
    }
    return render (request, template_name, context)

def delete_user(request, slug):
    template_name = 'accounts/delete_user.html'
    user = get_object_or_404(User, slug = slug)
    user.delete()
    return redirect('accounts:usuarios-cadastrados')
    context = {
        'user': user
    }
    return render(request, template_name, context)

################################### LOGIN/LOGOUT USER ################################### 

def user_login(request):
    template_name = 'accounts/login.html'
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        user = authenticate(request, username = username , password = password)
        teste = request.user.username
        if user is not None:
            login(request, user)
            return redirect('accounts:usuarios-cadastrados')
    else:
    #messages.error(request, 'Usuario ou senha invalidos. Tente novamente.')
        return render(request,template_name)

def user_logout(request):
    logout(request)
    return redirect('accounts:login')

RCJ/accounts/templates/accounts/base.html
<!DOCTYPE HTML>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  {% block styles%}{% endblock%}
  <title>
    {% block title%}
    Phoenix
    {% endblock%}
  </title>
</head>

<body>
  {% if user.get_nivel == 5 %} <!-- navbar operador-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#"><img src="{% static 'img/home.png' %}" width="50" height="50"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
      aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:implantar_ficha' %}">implantar ficha</a>
        </li>
      </ul>
      <div class="my-2 my-lg-0">
        <img src="{% static 'img/login.png' %}" width="50" height="50">
        <div class="btn-group">
          <button type="button" class="btn btn-sucess dropdown-toggle" data-toggle="dropdown">
            {{ user.get_full_name }} <span class="carret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <br>
  <br>
  <br>
  {%endif%}
  {% if user.get_nivel == 4 %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#"><img src="{% static 'img/home.png' %}" width="50" height="50"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
      aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:implantar_ficha' %}">implantar ficha</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">fila</a>
        </li>
      </ul>
      <div class="my-2 my-lg-0">
        <img src="{% static 'img/login.png' %}" width="50" height="50">
        <div class="btn-group">
          <button type="button" class="btn btn-sucess dropdown-toggle" data-toggle="dropdown">
            {{ user.get_full_name }} <span class="carret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <br>
  <br>
  <br>
  {%endif%}
  {%block conteudo%}{% endblock %}
  <br>
  <br>
  <br>
  <div class="rodape">
    <footer>
      <hr>
      <br>
      <div class="row">
          <div class="col"> &copy; RSC Solutions 2020 </div>
          <div class="col-9"></div>
          <div class="col">Alimentado por: Phoenix</div>
        </div>
    </footer>
    <br>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  {% block scripts %}{%endblock%}
</body>

</html>

RCJ/accounts/templates/accounts/edit_user.html
{% extends "accounts/base.html"%}
{% load static %}
{% load widget_tweaks%}
    <!-- <link rel="stylesheet" href="estilo/estilo.css"> -->
    {% block styles%}
    <link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css'%}">
    {% endblock %}
    {% block title %}Cadastrar Usuarios{% endblock %}
    {% block conteudo%}
    <div class="container">
        <div class="panel">
            <div>
                <div class="cadastro_title">
                    <p>Cadastro de Usuarios</p>
                </div>
                <br>
            </div>

            <div class="form">
                <form method="POST" id="form-usuario">
                    {% csrf_token %}
                    <div>
                        <div>
                            <div class="cadastro_subtitle">
                                <br>
                                <p>Dados do Usuario</p>
                                <br>
                            </div>
                            <br>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label>Funcionario:</label>
                                {% render_field form1.funcionario class+="form-control"%}
                            </div>
                            <div class="form-group col">
                                <label>E-mail:</label>
                                {% render_field form1.email class+="form-control"%}
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="col-auto">
                                <label>Gestor:</label>
                                {% render_field form1.gestor class+="form-control"%}
                            </div>
                        </div>
                    </div>
                    <br>
                    <div>
                        <div>
                            <div class="cadastro_subtitle">
                                <br>
                                <p>Usuario e Senha</p>
                                <br>
                            </div>
                            <br>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-3"></div>
                        <div class="col-5">
                            <div>
                                <label>Usuario:</label>
                                {% render_field form1.username class+="form-control"%}
                            </div>
                            <div>
                                <label>Senha:</label>
                                {% render_field form2.new_password1 class+="form-control"%}
                            </div>
                            <div>
                                <label>Confirmação de senha:</label>
                                {% render_field form2.new_password2 class+="form-control"%}
                            </div>
                            <div>
                                <label>Nivel de acesso:</label>
                                {% render_field form1.nivel class+="form-control"%}
                            </div>
                        </div>
                        <div class="col-3"></div>
                    </div>
            </div>
            <br>
            <div class="row justify-content-md-center">
                <div class="col col-lg-2"></div>
                <div class="col-md-auto">
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
                <div class="col col-lg-2"></div>
            </div>
            <br>
            </form>
        </div>
    </div>
    </div>

{% endblock%}

RCJ/accounts/templates/accounts/list_user.html
{% extends 'accounts/base.html'%}
{% load static %}
{% load widget_tweaks %}
{% block styles%}
    <link rel="stylesheet" href="{% static 'css/list_user.css' %}">
    <link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css' %}"> 
{% endblock %}
{% block title %}Listagem de usuarios{% endblock %}
{% block conteudo %}
<div class="container">
  <div class="cadastro_title">
    Usuario cadastrado no Sistema
  </div>
  <br>
  <div class="panel">
      <table class="table table-bordered">
        <thead class="thead-light"> 
          <tr>
            <th>Funcionario</th> 
            <th>Usuario</th> 
            <th>Cargo</th>
            <th>Ações</th>
          </tr> 
    </thead>
    <tbody>
      {% for info in user_list %}
      <tr>
        <td>
          {{info.funcionario.name}}
        </td>
        <td>
          {{info.username}}
        </td> 
        <td>
          {{info.funcionario.cargo}}
        </td> 
        <td>
          <a class="btn-opc" href="{% url 'accounts:editar-usuario' info.slug %}">Editar</a>
          <a class="btn-opc" href="{% url 'accounts:deletar-usuario' info.slug %}">Apagar</a>
        </td>
      </tr>
        {%endfor%} 
    </tbody>
      </table>
</div>
</div>

{% endblock %}

RCJ/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- <link rel="stylesheet" href="estilo/estilo.css"> -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/label.css' %}">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>Phoenix Login</title>
</head>

<body class="fundo">

  <div class="container-fluid">
    <div class="">

      <div class="row align-items-center">
        <div class="col"></div>
        <div class="col">
          <form method="POST" class="form-signin panel">
            {% csrf_token %}
            <p class="text-center alert alert-light">Por favor, entre com seu usuario e senha</p>
            <div class="form-label-group">
              <input type="name" name="username" id="username" class="form-control" placeholder="Usuario" required
                autofocus>
              <label for="inputName">Usuario</label>

            </div>
            <div class="form-label-group">
              <input type="password" name="password" id="password" class="form-control" placeholder="Senha" required
                autofocus>
              <label for="inputPassword">Senha</label>
            </div>
            <div class="row align-items-center">
              <div class="col"></div>
              <div class="custom-control custom-checkbox col">
                <input type="checkbox" class="custom-control-input" id="remember-me">
                <label class="custom-control-label" for="remember-me">Lembrar-se</label>
              </div>
              <div class="col"></div>
            </div>
            <br>
            <div class="row align-items-center">
              <div class="col"></div>
              <button class="btn btn-lg btn-primary col" type="submit">Login</button>
              <div class="col"></div>
            </div>
            <!--  <p class="mt-5 mb-3 text-muted">&copy;</p> -->
          </form>
          <script src="{% static 'js/bootstrap.min.js' %}"></script>
          <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
          <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
          <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->
        </div>
        <div class="col">

        </div>
      </div>
    </div>
  </div>
</body>

</html>

RCJ/accounts/templates/accounts/logout.html
<a href="{% url 'accounts:cadastro-usuario'%}" >logout</a>

RCJ/accounts/templates/accounts/register_user.html
{% extends "accounts/base.html"%}
{% load static %}
{% load widget_tweaks%}
    <!-- <link rel="stylesheet" href="estilo/estilo.css"> -->
    {% block styles%}
    <link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css'%}">
    {% endblock %}
    {% block title %}Cadastrar Usuarios{% endblock %}
    {% block conteudo%}
    <div class="container">
        <div class="panel">
            <div>
                <div class="cadastro_title">
                    <p>Cadastro de Usuarios</p>
                </div>
                <br>
            </div>

            <div class="form">
                <form method="POST" id="form-usuario">
                    {% csrf_token %}
                    <div>
                        <div>
                            <div class="cadastro_subtitle">
                                <br>
                                <p>Dados do Usuario</p>
                                <br>
                            </div>
                            <br>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label>Funcionario:</label>
                                {% render_field form.funcionario class+="form-control"%}
                            </div>
                            <div class="form-group col">
                                <label>E-mail:</label>
                                {% render_field form.email class+="form-control"%}
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="col-auto">
                                <label>Gestor:</label>
                                {% render_field form.gestor class+="form-control"%}
                            </div>
                        </div>
                    </div>
                    <br>
                    <div>
                        <div>
                            <div class="cadastro_subtitle">
                                <br>
                                <p>Usuario e Senha</p>
                                <br>
                            </div>
                            <br>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-3"></div>
                        <div class="col-5">
                            <div>
                                <label>Usuario:</label>
                                {% render_field form.username class+="form-control"%}
                            </div>
                            <div>
                                <label>Senha:</label>
                                {% render_field form.password1 class+="form-control"%}
                            </div>
                            <div>
                                <label>Confirmação de senha:</label>
                                {% render_field form.password2 class+="form-control"%}
                            </div>
                            <div>
                                <label>Nivel de acesso:</label>
                                {% render_field form.nivel class+="form-control"%}
                            </div>
                        </div>
                        <div class="col-3"></div>
                    </div>
            </div>
            <br>
            <div class="row justify-content-md-center">
                <div class="col col-lg-2"></div>
                <div class="col-md-auto">
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
                <div class="col col-lg-2"></div>
            </div>
            <br>
            </form>
        </div>

    </div>

    </div>    
{% endblock%}