RCJ/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from RCJ.core import views as core_views

app_name = 'core'
urlpatterns = [
    
    #path('lista_funcionarios/', funcionarios_views.list_funcionarios, name = 'lista_funcionario'),
    path('implantar_ficha/', core_views.implanta_ficha_cliente, name = 'implantar_ficha'),
    path('cadastrar_produto/', core_views.create_produto, name = 'cadastrar_produto'),
    path('fila_clientes/', core_views.fila_clientes, name = 'fila_clientes'),
    path('tratar_cliente/<slug:slug>-<int:pk>', core_views.tratar_clientes, name = 'tratar_cliente'),
    #path('deletar_funcionario/<int:pk>-<slug:slug>', funcionarios_views.delete_funcionario, name = 'deletar_funcionario'),

]

RCJ/funcionarios/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from RCJ.funcionarios import views as funcionarios_views

app_name = 'funcionarios'
urlpatterns = [
    
    path('lista_funcionarios/', funcionarios_views.list_funcionarios, name = 'lista_funcionario'),
    path('cadastrar_funcionario/', funcionarios_views.create_funcionario, name = 'cadastro_funcionario'),
    path('editar_funcionario/<slug:slug>-<int:pk>', funcionarios_views.edit_funcionario, name = 'editar_funcionario'),
    path('deletar_funcionario/<slug:slug>-<int:pk>', funcionarios_views.delete_funcionario, name = 'deletar_funcionario'),

]

RCJ/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path


urlpatterns = [
    
    #path('usuarios/', include('RCJ.accounts.urls', namespace = 'accounts')),
    path('', include('RCJ.core.urls', namespace = 'core')),
    path('usuarios/', include('RCJ.accounts.urls', namespace = 'accounts')),
    path('funcionarios/', include('RCJ.funcionarios.urls', namespace = 'funcionarios')),
    path('admin/', admin.site.urls),
]

RCJ/core/models.py
from django.db import models

#from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.db.models import signals
from django.utils.text import slugify

class EnderecoCliente(models.Model):
    
    street = models.CharField('Rua', max_length = 50, null = False, blank = False)
    number = models.IntegerField('Numero', null = False, blank = False)
    complement = models.CharField('Complemento', max_length = 50, null = False, blank = False)
    neighborhood = models.CharField('Bairro', max_length = 50, null = False, blank = False)
    reference_point = models.CharField('Ponto de referência', max_length = 50, null = False, blank = True)
    city = models.CharField('Cidade', max_length = 50, null = False, blank = False)
    state = models.CharField('Estado', max_length = 50, null = False, blank = False)

class ContatoCliente(models.Model):
    
    telefone_1 = models.CharField('Telefone 1', max_length = 11, null = True, blank = True)
    telefone_2 = models.CharField('Telefone 2', max_length = 11, null = True, blank = True)
    email = models.EmailField('E-mail', max_length = 50, null = True, blank = True)

class Produto(models.Model):
    
    EMPRESA_CHOICES = (
        ('SKY','SKY'),
        ('OI','OI'),
        ('CLARO','CLARO'),
        ('TIM', 'TIM')
    )
    
    TIPO_PRODUTO_CHOICES = (
        ('TV','TV'),
        ('BANDA_LARGA','BANDA LARGA'),
        ('MOVEL','MOVEL')
    )
    
    name = models.CharField('Nome', max_length = 5, choices = EMPRESA_CHOICES, null = False, blank= False)
    plano = models.CharField('Plano', max_length = 50, null = False, blank = False)
    valor = models.DecimalField('Valor', max_digits=5, decimal_places=2)
    
    def __str__(self):
        return self.plano
    

class Client(models.Model):
    
    SEXO_CHOICES = (
        ('M','MASCULINO'),
        ('F','FEMININO')
    )
    
    slug = models.SlugField('atalho', max_length = 11, unique = True, null = False, blank = True)
    name = models.CharField('Nome', max_length = 50, blank = False)
    cpf = models.CharField('CPF', max_length = 11, blank = False, null = False, unique = True)
    rg = models.CharField('RG', max_length = 11, blank = False, null = False, unique = True)
    date_of_birth = models.DateField('Data de Nascimento')
    sex = models.CharField('Sexo', max_length = 1, choices = SEXO_CHOICES)
    endereco = models.OneToOneField("EnderecoCliente", verbose_name=("Endereço"), on_delete=models.CASCADE)
    contato = models.OneToOneField("ContatoCliente", verbose_name=("Contato"), on_delete=models.CASCADE)

    def __str__(self):
        return self.name

def client_pre_save_receiver(sender, instance, *args, **kwargs):
    teste = slugify(instance.name) + '-%s'  % instance.cpf 
    instance.slug = teste
    
pre_save.connect(client_pre_save_receiver, sender = Client)  
    
class InfoAuditoria(models.Model):
    
    STATUS_AUDITORIA_CHOICE = (
        ('APROVADA', 'APROVADA'),
        ('REPROVADA', 'REPROVADA'),
        ('CONSULTAR', 'CONSULTAR'),
        ('CANCELADO', 'CANCELADO'),
        ('DESISTENCIA', 'DESISTENCIA'),
        ('CHECKLIST', 'CHECKLIST'),
        ('PENDENTE', 'PENDENTE')
        
    )
    STATUS_POS_VENDA_CHOICE = (
        ('HABILITADO', 'HABILITADO'),
        ('DESISTENCIA', 'DESISTÊNCIA'),
        ('EM ROTA', 'EM ROTA'),
        ('AGUARDANDO PAGAMENTO','AGUARDANDO PAGAMENTO')
        
    )
    auditor = models.CharField('Auditor', max_length = 50, null = True, blank = True)
    status_auditoria = models.CharField('Status da Auditoria', max_length = 12, choices = STATUS_AUDITORIA_CHOICE, null = True, blank = False, default = 'PENDENTE')
    status_pos_venda =  models.CharField('Status Pós venda', max_length = 21, choices = STATUS_POS_VENDA_CHOICE, null = True, blank = False, default = 'AGUARDANDO PAGAMENTO')
    observacoes = models.TextField('Observações', max_length = 1000, null = True, blank = True)
    
    
class InfoVenda(models.Model):
    
    CANAL_DA_VENDA_CHOICE = (
        ('ATIVO', 'ATIVO'),
        ('PREDITIVO', 'PREDITIVO'),
        ('DISCADOR', 'DISCADOR'),
        ('LEAD', 'LEAD'),
        ('REDES SOCIAIS', 'REDES SOCIAIS')
    )
    
    ADESAO_CHOICE = (
        ('GRATIS','GRÁTIS'),
        ('INTEGRAL','INTEGRAL'),
        ('PARCIAL','PARCIAL')

    )
    FORMA_DE_PAGAMENTO_CHOICE = (
        ('CARTAO DE CREDITO','CARTÃO DE CRÉDITO'),
        ('DEBITO EM CONTA','DÉBITO EM CONTA'),
        ('BOLETO BANCÁRIO','BOLETO BANCÁRIO')
    )
    
    STATUS_VENDA_CHOICE = (
        ('PRE APROVADA','PRE APROVADA'),
        ('REPROVADA','REPROVADA'),
        
    )
    produto = models.ForeignKey(Produto, verbose_name=("Produto"), on_delete=models.CASCADE)
    cliente = models.ForeignKey(Client, verbose_name=("Cliente"), on_delete=models.CASCADE)
    canal_da_venda = models.CharField('Canal da venda', max_length = 14, choices = CANAL_DA_VENDA_CHOICE, null = False, blank = False)
    status_venda = models.CharField('Status da Venda', max_length = 14, choices = STATUS_VENDA_CHOICE, null = False, blank = False )
    info_auditoria = models.OneToOneField("InfoAuditoria", verbose_name=("Informação Auditoria"), on_delete=models.CASCADE)
    operador = models.CharField('Operador', max_length = 50, null = False, blank = False)
    supervisor = models.CharField('Supervisor', max_length = 50, null = False, blank = False)
    created_date = models.DateField('Data da venda', auto_now_add = True)
    adesao = models.CharField('Adesão', max_length = 10, choices = ADESAO_CHOICE, null = False, blank = False)
    forma_de_pagamento = models.CharField('Forma de pagamento', max_length = 17, choices = FORMA_DE_PAGAMENTO_CHOICE, null = False, blank = False)
    observacoes = models.TextField('Observações', max_length = 1000, null = True, blank = True)
    
    def set_operador(self, operador):
        self.operador = operador
        return operador 
    
         
    
    
    
    

RCJ/core/forms.py
from django import forms
from RCJ.core.models import EnderecoCliente, ContatoCliente, Produto, Client, InfoVenda, InfoAuditoria


class EnderecoClienteForm(forms.ModelForm):
    
    class Meta:
        
        model = EnderecoCliente
        fields = '__all__' 
        
class ContatoClientForm(forms.ModelForm):
    
    class Meta:
        
        model = ContatoCliente
        fields = '__all__' 
        
class ProdutoForm(forms.ModelForm):
    
    class Meta:
        
        model = Produto
        fields= '__all__'

class ClientForm(forms.ModelForm):
    
    class Meta:
        
        model = Client
        exclude = ('endereco', 'contato')
        
    
class InfoAuditoriaForm(forms.ModelForm):
    
    class Meta:
        
        model = InfoAuditoria
        exclude = {'auditor'}
        
class InfoVendaForm(forms.ModelForm):
    
    class Meta:
        
        model = InfoVenda
        exclude = ('cliente','status_auditoria','status_pos_venda','created_date','info_auditoria','operador','supervisor')
        """
        widgets = {'operador': forms.HiddenInput(),
                    'supervisor': forms.HiddenInput()}
        """

RCJ/core/views.py
from RCJ.core.forms import EnderecoClienteForm, ContatoClientForm, ProdutoForm, ClientForm, InfoVendaForm, InfoAuditoriaForm
from RCJ.core.models import EnderecoCliente, ContatoCliente, Client, InfoVenda, Produto, InfoAuditoria
from RCJ.accounts.models import User
from django.shortcuts import render, redirect, get_object_or_404


# Create your views here.
################################################# CRUD PRODUTO #########################################################################
def create_produto(request):
    template_name = 'core/create_produto.html'
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('#')
    else:
        form = ProdutoForm()
    context = {
        'form':form
    }
    return render(request, template_name, context)

def edit_produto(request, pk):
    template_name = 'core/edit_produto.html'
    produto = get_object_or_404(Produto, pk = pk)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance = produto)
        if form.is_valid():
            form.save()
        return redirect('core:cadastrar_produto')
    else:
        form = ProdutoForm(instance = produto)
    context = {
        'form':form
    }
    return render(request, template_name, context)

def delete_produto(request, pk):
    template_name = 'core/delete_produto.html'
    produto = get_object_or_404(Produto, pk = pk)
    if request.method == 'POST':
        produto.delete()
        return redirect('#')
    context = {
        'produto': produto
    }
    return render(request, template_name, context)

def list_produtos(request):
    template_name = 'core/list_produtos.html'
    produto = Produto.objects.all()
    context = {
        'produto': produto
    }
    return render(request, template_name, context)
#####################################################################################################################################################################

######################################################### CRUD FICHA CLIENTE ########################################################################################

def implanta_ficha_cliente(request):
    template_name = 'core/implanta_ficha.html'
    if request.method == 'POST':
        teste = InfoVenda()
        usuario = User.objects.get(username = request.user.get_username())
        print(usuario.gestor)
        operador = usuario.funcionario.name
        gestor = usuario.gestor
        form1 = ClientForm(request.POST)
        form2 = EnderecoClienteForm(request.POST)
        form3 = ContatoClientForm(request.POST)
        form4 = InfoVendaForm(request.POST)
        form5 = InfoAuditoriaForm(request.POST)
        print(form1.errors)
        print(form2.errors)
        print(form3.errors)
        print(form4.errors)
        print(form5.errors)
        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid():
            venda = form4.save(commit = False)
            cliente = form1.save(commit = False)
            endereco = form2.save()
            contato = form3.save()
            infoauditoria = form5.save()
            cliente.endereco = endereco
            cliente.contato = contato
            cliente.save()
            venda.cliente = cliente
            venda.info_auditoria = infoauditoria
            venda.supervisor = gestor
            venda.operador = operador
            venda.save()
            return redirect('#')
    else:
        form1 = ClientForm()
        form2 = EnderecoClienteForm()
        form3 = ContatoClientForm()
        form4 = InfoVendaForm()
        form5 = InfoAuditoriaForm()
    context = {
        'form1':form1,
        'form2':form2,
        'form3':form3,
        'form4':form4,
        'form5':form5
    }
    return render(request, template_name, context)

def fila_clientes(request):
    template_name = 'core/fila_cliente.html'
    infovenda = InfoVenda.objects.all()
    context = {
        'fila':infovenda
    }
    return render(request, template_name, context)

def tratar_clientes(request, slug, pk):
    template_name = 'core/tratar_cliente.html'
    cliente = get_object_or_404(Client, slug = slug)
    endereco = get_object_or_404(EnderecoCliente, pk = pk)
    contato = get_object_or_404(ContatoCliente, pk = pk)
    infovenda = get_object_or_404(InfoVenda, pk = pk)
    infoauditoria = get_object_or_404(InfoAuditoria, pk = pk)
    if request.method == 'POST':
        form1 = ClientForm(request.POST, instance = cliente)
        form2 = EnderecoClienteForm(request.POST, instance = endereco)
        form3 = ContatoClientForm(request.POST, instance = contato)
        form4 = InfoVendaForm(request.POST, instance = infovenda)
        form5 = InfoAuditoriaForm(request.POST, instance = infoauditoria)
        
        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid():
            cliente = form1.save(commit = False)
            venda = form4.save(commit = False)
            endereco = form2.save()
            contato = form3.save()
            infoauditoria = form5.save()
            cliente.endereco = endereco
            cliente.contato = contato
            cliente.save()
            venda.cliente = cliente
            venda.info_auditoria = infoauditoria
            venda.save()
            return redirect('#')
    else:
        form1 = ClientForm(instance = cliente)
        form2 = EnderecoClienteForm(instance = endereco)
        form3 = ContatoClientForm(instance = contato)
        form4 = InfoVendaForm(instance = infovenda)
        form5 = InfoAuditoriaForm(instance = infoauditoria)
    context = {
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'form5': form5,
    }
    return render(request, template_name, context)
                
            
            
        

RCJ/core/templates/core/create_produto.html
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
     
    <button class="btn btn-primary">Enviar</button>
</form>

{% endblock content %}

RCJ/core/templates/core/fila_cliente.html
{% extends 'accounts/base.html'%}
{% load static %}
{% load widget_tweaks %}
{% block styles%}
    <link rel="stylesheet" href="{% static 'css/list_user.css' %}">
    <link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css' %}"> 
{% endblock %}
{% block title %}Fila de Clientes{% endblock %}
{% block conteudo %}
<div class="container">
  <div class="cadastro_title">
    Fila
  </div>
  <br>
  <div class="panel">
      <table class="table table-bordered">
        <thead class="thead-light"> 
          <tr>
            <th>Cliente</th> 
            <th>Operador</th> 
            <th>Supervisor</th>
            <th>Status</th>
            <th>Ações</th>
          </tr> 
    </thead>
    <tbody>
      {% for info in fila %}
      {% if info.info_auditoria.status_audutoria == 'PENDENTE'%}
      <tr>
        <td>
          {{info.cliente.name}}
        </td>
        <td>
          {{info.operador}}
        </td> 
        <td>
          {{info.supervisor}}
        </td> 
        <td>
          {{info.status_venda}}
        </td> 
        <td>
          <a class="btn-opc" href="{% url 'core:tratar_cliente' info.cliente.slug info.id %}">Tratar cliente</a>
        </td>
      </tr>
        {%endif%}
        {%endfor%} 
    </tbody>
      </table>
</div>
</div>

{% endblock %}



<a href=>back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>CPF</th>
      <th>Status Operador</th>
      <th>Status Auditoria</th>
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'funcionarios:cadastro_funcionario'%}">add</a>
    {% for b in fila %}
    <tr>
      <td>{{ b.cliente.name }}</td>
      <td>{{ b.cliente.cpf }}</td>
      <td>{{ b.status_venda }}</td>
      <td>{{ b.info_auditoria.status_auditoria}}</td>
      <td>
        <a href="{% url 'core:tratar_cliente' b.cliente.slug b.id %}">editar</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

RCJ/core/templates/core/implanta_ficha.html
{% extends 'accounts/base.html'%}
{% load static%}
{% load widget_tweaks%}
<!-- <link rel="stylesheet" href="estilo/estilo.css"> -->
{% block styles%}
<link rel="stylesheet" href="{% static 'css/cadastrar_usuario.css'%}">
<link rel="stylesheet" href="{% static 'css/implantar_ficha.css'%}">
{% endblock %}
{% block title %}Implantar Ficha{% endblock %}
{% block conteudo %}
<div class="container">
    <div class="panel">
        <div>
            <div class="cadastro_title">
                <p>Cadastro de clientes</p>
            </div>
            <br>
        </div>
        <div class="form">
            <form method="POST" id="form-funcionario">
                {% csrf_token %}
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados do pessoais</p>
                            <br>
                        </div>
                        <br>
                    </div>

                    <div class="form-row">
                        <div class="col">
                            <label>Nome:</label>
                            {% render_field form1.name class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Data de nascimento:</label>
                            {% render_field form1.date_of_birth class+="form-control"%}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label>Sexo:</label>
                            {% render_field form1.sex class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Rg:</label>
                            {% render_field form1.rg class+="form-control"%}
                        </div>
                        <div class="col">
                            <label>Cpf:</label>
                            {% render_field form1.cpf class+="form-control"%}
                        </div>
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados de endereco</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label>Rua:</label>
                        {% render_field form2.street class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Numero:</label>
                        {% render_field form2.number class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Complemento:</label>
                        {% render_field form2.complement class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Ponto de referencia:</label>
                        {% render_field form2.reference_point class+="form-control"%}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Bairro:</label>
                        {% render_field form2.neighborhood class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Cidade:</label>
                        {% render_field form2.city class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Estado:</label>
                        {% render_field form2.state class+="form-control"%}
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados de contato</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Telefone 1:</label>
                        {% render_field form3.telefone_1 class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Telefone 2:</label>
                        {% render_field form3.telefone_2 class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Email:</label>
                        {% render_field form3.email class+="form-control"%}
                        
                    </div>
                </div>
                <br>
                <div>
                    <div>
                        <div class="cadastro_subtitle">
                            <br>
                            <p>Dados de produto</p>
                            <br>
                        </div>
                        <br>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Produto:</label>
                        {% render_field form4.produto class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Status:</label>
                        {% render_field form4.status_venda class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Canal da venda:</label>
                        {% render_field form4.canal_da_venda class+="form-control"%} 
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Adesão:</label>
                        {% render_field form4.adesao class+="form-control"%}
                    </div>
                    <div class="col">
                        <label>Forma de pagamento:</label>
                        {% render_field form4.forma_de_pagamento class+="form-control"%}
                    </div>  
                </div>
                <div class="form-row">
                    <div class="col">
                    </div>
                    <div class="col"></div>  
                </div>
                <div class="form-row">
                    <div class="col">
                        {% render_field form5.status_auditoria class+="form-control"%}
                    </div>
                    <div class="col">
                        {% render_field form5.status_pos_venda class+="form-control"%}
                    </div>  
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Observações:</label>
                        {% render_field form4.observacoes class+="form-control"%}
                    </div>
                    <div class="col"></div>  
                </div>
        </div>
        <br>
        <br>
        <div class="row justify-content-md-center">
            <div class="col col-lg-2"></div>
            <div class="col-md-auto">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
            <div class="col col-lg-2"></div>
        </div>
        <br>
        </form>
    </div>
</div>
</div>
</div>

{% endblock conteudo %}